# Generated by Django 3.0.5 on 2020-04-12 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, unique=True, upload_to='')),
                ('antenna_position', models.CharField(max_length=500, null=True)),
                ('connected_rrh_serial', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('fcc_id', models.CharField(max_length=500, null=True)),
                ('site_common_name', models.CharField(max_length=500, null=True)),
                ('market', models.CharField(max_length=500, null=True)),
                ('enode_b_id', models.CharField(max_length=500, null=True)),
                ('ptn', models.CharField(max_length=500, null=True)),
                ('release', models.CharField(max_length=500, null=True)),
                ('cross_sector_redundency', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_operating_band', models.CharField(max_length=500, null=True)),
                ('technology_cell_id', models.CharField(max_length=500, null=True)),
                ('parent_ref_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_ref_number_tech', to='core.Process', to_field='ref_number')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='test_image')),
                ('parent_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_antenna_file', to='core.Document', to_field='document')),
            ],
        ),
        migrations.CreateModel(
            name='Ret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ret_position', models.CharField(max_length=500, null=True)),
                ('antenna_serial_number', models.CharField(max_length=500, null=True)),
                ('device_serial', models.CharField(max_length=500, null=True)),
                ('antenna_model', models.CharField(max_length=500, null=True)),
                ('aisg_version', models.CharField(max_length=500)),
                ('ret_name', models.CharField(max_length=500, null=True)),
                ('station_id', models.CharField(max_length=500, null=True)),
                ('tilt_range', models.CharField(max_length=500, null=True)),
                ('electrical_tilt', models.CharField(max_length=500, null=True)),
                ('usid', models.CharField(max_length=500, null=True)),
                ('sector_id', models.CharField(max_length=500, null=True)),
                ('relative_antenna_position', models.CharField(max_length=500, null=True)),
                ('bearing', models.CharField(max_length=500)),
                ('operating_band', models.CharField(max_length=500, null=True)),
                ('band', models.CharField(max_length=500, null=True)),
                ('technology', models.CharField(max_length=500, null=True)),
                ('eutran_cell_id', models.CharField(max_length=500, null=True)),
                ('ret_sub_unit', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=500)),
                ('hw_version', models.CharField(max_length=500)),
                ('installation_date', models.CharField(max_length=500, null=True)),
                ('installer_id', models.CharField(max_length=500, null=True)),
                ('ret_cell_id', models.CharField(max_length=500, null=True)),
                ('parent_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_file', to='core.Document', to_field='document')),
                ('parent_ref_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_ref_number', to='core.Process', to_field='ref_number')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process', to='core.Process', to_field='ref_number'),
        ),
    ]
