# Generated by Django 3.0.3 on 2020-02-16 04:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('session_name', models.CharField(max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ret_name', models.CharField(max_length=500, null=True)),
                ('rret_name', models.CharField(max_length=500, null=True)),
                ('station_id', models.CharField(max_length=500, null=True)),
                ('aisg_version', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('bearing', models.CharField(max_length=500)),
                ('hw_version', models.CharField(max_length=500)),
                ('parent_ref_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_ref_number', to='core.Process', to_field='ref_number')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='')),
                ('position', models.CharField(choices=[('alpha_pos_1', 'alpha_pos_1'), ('alpha_pos_2', 'alpha_pos_2')], max_length=500, null=True)),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process', to='core.Process', to_field='ref_number')),
            ],
        ),
    ]
