# Generated by Django 3.0.3 on 2020-02-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ret',
            name='ret_position',
            field=models.ManyToManyField(null=True, related_name='ret_position', to='core.Document'),
        ),
    ]
