# Generated by Django 3.0.3 on 2020-02-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ret_ret_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='ret',
            name='sector_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
